version: "3.3"
services:
  sync-up-dev:
    container_name: sync-up-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - '/etc/ssl/certs:/etc/ssl/certs:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '13003:13003'
    environment:
      - DEBUG=true
      - SYNCUP_DB=sqlite
      - SYNCUP_DB_DSN=/data/sqlite.db
      - SYNCUP_USERNAME=admin
      - SYNCUP_PASSWORD=admin
      - SYNCUP_SECRET_KEY=b8555b47784f612c36c7ca5561c9a3cfd806800a
      - SYNCUP_PORT=13003
      - SYNCUP_redis1_TYPE=redis-rdb-c
      - SYNCUP_redis1_RDB_FILE_PATH=/data/dump.rdb
      - SYNCUP_redis1_CONTAINER=redis
      - SYNCUP_redis1_CRON=0 */30 * * * *
      - SYNCUP_redis1_LOCAL_DIR_PATH=/temp
      - SYNCUP_redis1_PASSWORD=E8sJCHto2VNYZzin
      - SYNCUP_redis1_RC=rclone
      - SYNCUP_redis1_RC_DIR_PATH=/backup
      - SYNCUP_redis1_RC_REMOTE_NAME=alist
      - SYNCUP_redis1_RC_REMOTE_PATH=/backup/redis
